[build]
  publish = "."

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/favicon.ico"
  to = "/assets/images/favicon/favicon.ico"
  status = 301

[[redirects]]
  from = "/apple-touch-icon.png"
  to = "/assets/images/favicon/apple-touch-icon.png"
  status = 301

[[redirects]]
  from = "/android-chrome-192x192.png"
  to = "/assets/images/favicon/android-chrome-192x192.png"
  status = 301

[[redirects]]
  from = "/android-chrome-512x512.png"
  to = "/assets/images/favicon/android-chrome-512x512.png"
  status = 301